---
title: "Lei_Zhuo_STAT425_HW30"
author: "Zhuo Feng Lei (zlei5)"
date: "4/19/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stats)
```

## Question 1a
```{r}
x = c(1.34,-1.38,-0.19,-0.44,1.90,-0.80,0.91,0.26,1.37,-1.62,-0.96,1.90,0.99,1.96,-1.57,1.51,-1.61,-1.02,-0.92,-1.87,1.73,-1.23,-1.24,0.22
,1.42)
y = c(1,0,0,1,1,0,1,1,1,0,1,1,1,1,1,0,0,0,0,0,1,0,0,1,0)
data = data.frame(x,y)
```

```{r}
fit1 = glm(y~x,family = binomial,data = data)
summary(fit1)
coefficients(fit1)
```
$\hat{\beta}_0$ is .1158087. $\hat{\beta}_1$ is 1.0285165. 

## Question 1b
```{r}
confint(fit1)
```

## Question 1c
```{r}
exp(.1158+1.0285)/(1+exp(.1158+1.0285))
```

## Question 1d
```{r}
b = function(beta,x){
  b0 = beta[1]
  b1 = beta[2]
  log = sum(exp(b0+b1*x)/(1+exp(b0+b1*x)))
  return(-log)
}
optim(c(.25,.75),fn=b,x=x)
```

## Question 1e
```{r}
plot(seq(-3,3,.1),-1*sapply(seq(-3,3,.1),FUN=b,beta=c(0,1)),type='l')
```
Seems to reach maximum when $\hat{\beta}_1$ is at 3.
